driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-8.5
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: package
  run_list:
  - recipe[test]
- name: source
  run_list:
  - recipe[test]
  attributes:
    haproxy:
      install_method: source
- name: app_lb
  run_list:
  - recipe[haproxy::app_lb]
