driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
    driver:
      box: bento/centos-6.8

  - name: centos-7
    driver:
      box: bento/centos-7.3

  - name: debian-8
    driver:
      box: bento/debian-8.6

  - name: fedora-25
    driver:
      box: bento/fedora-25

  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04

  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

suites:
- name: package
  run_list:
    - recipe[test]
- name: source
  run_list:
    - recipe[test]
  attributes:
    haproxy:
      install_method: source
- name: app_lb
  run_list:
    - recipe[haproxy::app_lb]
