config:
  ul-indent: false # MD007
  line-length: false # MD013
  no-duplicate-heading: false # MD024
  reference-links-images: false # MD052
  no-multiple-blanks: false # MD012 Ignore due to release-please
ignores:
  - .github/copilot-instructions.md
