#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "haproxy", :path => '.'

cookbook "apt"
cookbook "yum"
cookbook "haproxy-test", :path => './test/cookbooks/haproxy-test'
