---
name: md-links

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  md-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-verbose-mode: "yes"
          folder-path: "documentation"
